package com.learning.controllers;

import com.learning.models.Timers;
import com.learning.utils.TimersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/exercises") // This means URL's start with /demo (after Application path)
public class TimersController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TimersRepository timersRepository;

    @RequestMapping("/view")
    public @ResponseBody
    Timers getTimersId(@RequestParam Integer id) {
        return timersRepository.findOne(id);
    }

    @RequestMapping("/list")
    public String getTimersList(Model model) {
        model.addAttribute("timers", timersRepository.findAll());
        return "exercises_list";
    }

    @RequestMapping("/test")
    public String getTimersTest(Model model) {
        model.addAttribute("timers", timersRepository.findAll());
        return "test";
    }

    @PostMapping("/test_result")
    @ResponseBody
    public String timersSubmit(ArrayList<Timers> timers) {
        System.out.println(timers.size());
        return "redirect:/exercises/list";
    }
}
