package com.learning.controllers;

import com.learning.models.Timers;
import com.learning.utils.TimersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/exercises") // This means URL's start with /demo (after Application path)
public class TimersController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TimersRepository timersRepository;

    @RequestMapping("/view")
    public @ResponseBody
    Timers getTimersId(@RequestParam Integer id) {
        return timersRepository.findOne(id);
    }

    @RequestMapping("/list")
    public String getTimersList(Model model) {
        model.addAttribute("timers", timersRepository.findAll());
        return "exercises_list";
    }

    @RequestMapping("/test")
    public String getTimersTest(Model model) {
        model.addAttribute("timers", timersRepository.findAll());
        System.out.println(timersRepository.findAll());
        return "test";
    }

//    @PostMapping("/test_result")
//    @ResponseBody
//    public String timersSubmit(ArrayList<Timers> timers) {
//        System.out.println(timers.size());
//        return "exercises_list";
//    }

    @RequestMapping(value="/test_result", method=RequestMethod.POST)
    public String timersSubmit(HttpServletRequest request, Model model, @ModelAttribute ArrayList<Timers> timers) {
//        timersRepository.
        System.out.println("Inside POST");
        System.out.println(timers);
        System.out.println(request.getParameter("timers"));
//        Map<String,String[]> map =request.getParameterMap();
//        for(String key: map.keySet()){
//            String[] values = map.get(key);
//            System.out.println(key+": ");
//            for(String value: values){
//                System.out.println("--->"+ value);
//            }
//        }
        model.addAttribute(timers);
        return "redirect:/exercises/list";
    }
}
